# Generated by Django 4.0 on 2021-12-17 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phonehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneinfo',
            name='linkHistory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='phones.phonehistory'),
        ),
    ]
